spring.application.name=wc-exihibit

# ==========================
# MongoDB
# ==========================

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=wc_exihibit

spring.data.mongodb.username=admin
spring.data.mongodb.password=admin

spring.data.mongodb.authentication-database=admin

# ==========================
# Kafka
# ==========================

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=wc-exihibit-group

spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

spring.kafka.consumer.properties.spring.deserializer.key.delegate.class=org.apache.kafka.common.serialization.StringDeserializer

spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=*

spring.kafka.consumer.properties.spring.json.value.default.type=com.exihibition.wc_exihibit.dtos.MatchResultMessage

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer

spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# ==========================
# Server
# ==========================

server.port=8010

# ==========================
# Logging
# ==========================

logging.level.org.springframework.data.mongodb.core.MongoTemplate=INFO

logging.level.org.apache.kafka=INFO