spring.application.name=wc-predict

spring.mongodb.uri=mongodb://admin:admin@localhost:27019/wc_predict?authSource=admin

server.port=8012

spring.graphql.graphiql.enabled=true
spring.graphql.http.path=/graphql