version: '3.8'

services:

  # =========================
  # PostgreSQL
  # =========================
  postgresql:
    container_name: wc_pg_sql
    image: postgres:15
    environment:
      POSTGRES_USER: alibou
      POSTGRES_PASSWORD: alibou
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5437:5432"
    networks:
      - wc-environment
    restart: unless-stopped


  # =========================
  # PGAdmin
  # =========================
  pgadmin:
    container_name: wc_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5054:80"
    networks:
      - wc-environment
    restart: unless-stopped


  # =========================
  # ZooKeeper
  # =========================
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "22181:2181"
    networks:
      - wc-environment


  # =========================
  # Kafka
  # =========================
  kafka:
    image: confluentinc/cp-kafka:7.3.0   # ✅ FIXED VERSION
    container_name: wc_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29093:29093"
    environment:

      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29093,PLAINTEXT_HOST://0.0.0.0:9092

      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://wc_kafka:29093,PLAINTEXT_HOST://localhost:9092

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

    networks:
      - wc-environment


  # =========================
  # Kafka UI
  # =========================
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka_ui
    depends_on:
      - kafka
    ports:
      - "8085:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: wc-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: wc_kafka:29093
    networks:
      - wc-environment


networks:
  wc-environment:
    driver: bridge

volumes:
  postgres:
  pgadmin: